name: CI
on:
  push:
    branches:
      - stable
      - unstable
      - test-minver
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@minver
    with:
      install-command: 'nimble --resolver:minver install -y --depsOnly'
      test-command: |
        nim -v
        nimble list --installed --version
        env NIMLANG=c nimble test
        env NIMLANG=c nimble test_generic_futex
        env NIMLANG=c nimble test_bench
