name: CI
on:
  push:
    branches:
      - stable
      - unstable
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        nimble test_asan
        nimble test
        nimble test_generic_futex
        nimble test_bench
