name: CI
on:
  push:
    branches:
      - stable
      - unstable
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        nim -v
        nimble list --installed --version
        env NIMLANG=c nimble test
        env NIMLANG=c nimble test_bench
